const colors = [ //cardtypes //Madfut22 1.2.5
    "bundesliga_potm",
    "card_shimmer",
    "default",
    "ecl_rttf",
    "epl_potm",
    "eredivisie_potm",
    "europa_motm",
    "europa_rttf",
    "europa_tott",
    "fantasy",
    "fantasy_2",
    "flashback",
    "fut_birthday",
    "fut_captains",
    "fut_champs",
    "fut_champs_silver",
    "fut_hero",
    "fut_hero_captains",
    "futties",
    "futties_winner",
    "future_icon",
    "future_stars",
    "gold",
    "headliners",
    "hero",
    "icon",
    "icon_moments",
    "laliga_potm",
    "league_objectives",
    "libertadores",
    "ligue1_potm",
    "ltm",
    "ltm_234577",
    "ltm_240833",
    "ltm_242641",
    "ltm_246174",
    "ltm_251570",
    "ltm_252961",
    "ltm_255001",
    "ltm_258826",
    "ltm_262053",
    "ltm_264240",
    "madfut_icon",
    "meta",
    "motm",
    "next_generation",
    "numbersup",
    "objectives",
    "otw",
    "pack_opener_new",
    "player_moments",
    "pro_player",
    "rare_bronze",
    "rare_gold",
    "rare_silver",
    "record_breaker",
    "rulebreakers",
    "sbc",
    "sbc_premium",
    "seriea_potm",
    "shapeshifters",
    "showdown",
    "signature_signings",
    "silver",
    "silver_stars",
    "special",
    "squad_foundations",
    "sudamericana",
    "throwback",
    "tots",
    "tots_libertadores",
    "tots_moments",
    "totw_gold",
    "totw_silver",
    "toty",
    "toty_nominee",
    "ucl_motm",
    "ucl_rttf",
    "ucl_tott",
    "versus_fire",
    "versus_ice",
    "winter_wildcard",
]

const tradingMessageIds = { //Madfut22 1.2.5
  15: "I LOVE MADFUT",
  14: "I GIVE CARDS FOR FREE",
  13: "I HAVE 0 DUPES",
  12. "I FINISHED 0 TRADES",
  11: "I AM LEVEL 0",
  10: "I DONT HAVE PACKS",
  9: "NO COINZ PLZ",
  8: "NO PACKZ PLZ",
  7: "UCL CARDS PLZ",
  6: "TOP SPECIALS PLZ",
  5: "I WANT COINS",
  4: "I WANT PACKS",
  3: "I WANT CARDS",
  2: "I ONLY WANT WISHLIST",
  1: "I HAVE 0% COLLECTION",
}

const packetActionHeaders = { //Madfut22
  readyToStart: "b", 
  tradingStartAnimatingOutline: "c", 
  tradingStopAnimatingOutline: "d",
  tradingPickedCard: "e",
  tradingDeletedOutline: "f",
  tradingThumbs: "g",
  tradingReady: "h",
  tradingMakeChanges:  "i",
  tradingCompleteTradeCancel: "j",
  tradingCompleteTradeAccept: "k",
  tradingHandshake: "l",
  tradingEmoteText: "m",
  tradingEmoteEmoji: "n",
  tradingPickedPack: "o",
  tradingBiddingWarBid: "p",
  tradingCoinsMessage: "r",
  tradingStartAnimatingCoins: "s",
  tradingStopAnimatingCoins: "t",
  fatalCountdown: "u",
  fatalPick: "v"
}

const positions = [ //Madfut22 1.2.5
  "CAM",
  "CB",
  "CDM",
  "CF",
  "CM",
  "GK",
  "LB",
  "LF",
  "LM",
  "LW",
  "LWB",
  "RB",
  "RF",
  "RM",
  "RW",
  "RWB",
  "ST",
]
